# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI - Lucee 5.4

on: [push, pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      luceeVersion: light-6.0.0.381-SNAPSHOT
      luceeVersionQuery: 5.4/all/light
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: lucee-script-runner-maven-cache
    - name: Cache Lucee files
      uses: actions/cache@v4
      with:
        path: ~/work/_actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads
    - name: Build with Ant
      run: ant -noinput -verbose -buildfile build.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: esapi-lex
        path: dist/*.lex
    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee
    - name: Run Lucee Test Suite, testLabels="esapi"
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{ env.luceeVersion }}
        luceeVersionQuery: ${{ env.luceeVersionQuery }}
        extensionDir: ${{ github.workspace }}/dist
      env:
        testLabels: esapi
        testAdditional: ${{ github.workspace }}/tests
